version: 1.0.{build}
os: Visual Studio 2015
build:
  publish_nuget: false
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: KNJnbjUxOB4biL8fy8bYbTaiALnmaWQn7LPXt+mBzeUISU5RvOFi7q2t0MNn5nA5
  skip_symbols: false
  artifact: /.*\.nupkg/
